import React from 'react';
import Head from 'next/head';
import Link from 'next/link';

const header = () => {
	return (
		<>
			<Head>
			<link rel="preconnect" href="https://cdnjs.cloudflare.com/ajax/libs/antd/4.17.0-alpha.3/antd.min.js"/>
				<title>SpaceX App</title>
				<meta name='description' content='Generated by create next app' />
				{/* <link rel='icon' href='/favicon.ico' /> */}
			</Head>
			<header>
				<Link href='/'>Home</Link>
			</header>
		</>
	);
};

export default header;
